// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqGOCqANIBB14dUyqAJ3ij6lWFOE_16-8',
    appId: '1:554572323808:android:16c8c3a4c8849ff7a76985',
    messagingSenderId: '554572323808',
    projectId: 'cafetopia-1',
    storageBucket: 'cafetopia-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvtBpGHh4GyKcZWt8I3pzkm-H4pkjXw-0',
    appId: '1:554572323808:ios:8299ea8e36ca8bf1a76985',
    messagingSenderId: '554572323808',
    projectId: 'cafetopia-1',
    storageBucket: 'cafetopia-1.appspot.com',
    iosBundleId: 'by.bsuir.cafetopiaFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTbWJtCPnbJjyH6AYC85h2jZ-wGbdfdlk',
    appId: '1:554572323808:web:0c596126f5c1d3e2a76985',
    messagingSenderId: '554572323808',
    projectId: 'cafetopia-1',
    authDomain: 'cafetopia-1.firebaseapp.com',
    storageBucket: 'cafetopia-1.appspot.com',
    measurementId: 'G-RR0ZDWNBYN',
  );
}
